# Generated by Django 4.2.13 on 2026-06-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_recipients_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Recipient',
                'verbose_name_plural': 'Alert Recipients',
                'db_table': 'alert_recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('90_days', '90 Days Before Due'), ('30_days', '30 Days Before Due'), ('20_days', '20 Days Before Due')], db_index=True, max_length=10)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(db_index=True)),
                ('calibration_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='instruments.calibrationrecord')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['instrument', 'trigger_type', 'year'], name='notificatio_instrum_7c6c23_idx'), models.Index(fields=['calibration_record', 'trigger_type', 'recipient_email', 'year'], name='notificatio_calibra_56d464_idx'), models.Index(fields=['status', 'sent_at'], name='notificatio_status_be9b86_idx')],
            },
        ),
    ]
