# Generated by Django 4.2.13 on 2026-06-15 16:45

import apps.instruments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=25)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'db_table': 'instruments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calibrated_on', models.DateField()),
                ('calibration_due_date', models.DateField(db_index=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=apps.instruments.models.calibration_report_upload_path, validators=[apps.instruments.models.validate_pdf_file])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_records_created', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_records', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Calibration Record',
                'verbose_name_plural': 'Calibration Records',
                'db_table': 'calibration_records',
                'ordering': ['-calibration_due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['name', 'status'], name='instruments_name_9e26b3_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['is_deleted', 'status'], name='instruments_is_dele_bc97a1_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['serial_number'], name='instruments_serial__ba2f83_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['calibration_due_date'], name='calibration_calibra_9bb57a_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['instrument', 'calibration_due_date'], name='calibration_instrum_dcd9dd_idx'),
        ),
    ]
