'use client';

import { useState, FormEvent, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Upload, ChevronDown, X, FileText } from 'lucide-react';
import api from '@/lib/api';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';

const INSTRUMENT_NAMES = [
  'Shimadzu GC-01 UOP 744',
  'Shimadzu GC-02 UOP 744',
  'SHIMADZU GC-03 UOP 744 & ASTM D7504',
  'Shimadzu GC-04 ASTM D7504',
  'Shimadzu GC SCD',
  'Shimadzu HPLC ASTM D7884',
  'Agilent HPLC ASTM D7884',
  'Agilent GC-01 UOP 621',
  'Agilent GC-02 UOP 690',
  'Agilent GC-03 UOP 720',
  'Agilent GC-04 UOP 798',
  'Agilent GC-05 UOP 744',
  'Agilent GC-06 UOP 744',
  'Agilent GC-07 UOP 831',
  'Agilent GC-08 ASTM D-6730 DHA PIONA',
  'Agilent GC-09 UOP 931',
  'Agilent GC-10',
  'Agilent GC-11 ASTM D-6730 DHA PIONA',
  'Agilent GC-12 UOP 744',
  'Agilent GC-13 INVISTA 1020',
  'Agilent GC-14 INVISTA 1020',
  'Agilent GC-15 INVISTA 1990',
  'Agilent GC-16 INVISTA 2210',
];

const DEPARTMENTS = ['PX-PTA Lab'];

/**
 * Two-step form: creates Instrument then its first CalibrationRecord.
 * - Instrument name: choose from dropdown or type a custom name
 * - Serial number: auto-generated by the backend (INST-XXXX)
 * - Department: fixed dropdown (PX-PTA Lab)
 * - Location / Description removed
 * - Calibration report: accepts all document types, no size limit
 */
export function InstrumentForm() {
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  // Name field: dropdown + custom input toggle
  const [nameMode, setNameMode] = useState<'dropdown' | 'custom'>('dropdown');
  const [selectedName, setSelectedName] = useState('');
  const [customName, setCustomName] = useState('');

  const [formData, setFormData] = useState({
    department: DEPARTMENTS[0],
    calibrated_on: '',
    calibration_due_date: '',
    notes: '',
  });

  const [reportFile, setReportFile] = useState<File | null>(null);

  function updateField(field: string, value: string) {
    setFormData((prev) => ({ ...prev, [field]: value }));
  }

  const instrumentName = nameMode === 'dropdown' ? selectedName : customName;

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size === 0) {
      setError('The selected file is empty.');
      return;
    }
    setError('');
    setReportFile(file);
  }

  function clearFile() {
    setReportFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError('');

    const name = instrumentName.trim();
    if (!name) {
      setError('Please select or enter an instrument name.');
      return;
    }
    if (!formData.calibrated_on || !formData.calibration_due_date) {
      setError('Both calibration dates are required.');
      return;
    }
    if (formData.calibration_due_date <= formData.calibrated_on) {
      setError('Calibration due date must be after the calibrated on date.');
      return;
    }

    setIsSubmitting(true);

    try {
      // Step 1: Create instrument (serial_number auto-generated by backend)
      const instrumentResponse = await api.post('/instruments/', {
        name,
        department: formData.department,
        status: 'active',
      });

      const instrumentId = instrumentResponse.data.data.id;

      // Step 2: Create the calibration record (with optional file)
      const calibrationFormData = new FormData();
      calibrationFormData.append('instrument', instrumentId);
      calibrationFormData.append('calibrated_on', formData.calibrated_on);
      calibrationFormData.append('calibration_due_date', formData.calibration_due_date);
      if (formData.notes) calibrationFormData.append('notes', formData.notes);
      if (reportFile) calibrationFormData.append('report_file', reportFile);
      
      await api.post('/instruments/calibrations/', calibrationFormData);

      router.push('/admin/instruments');
    } catch (err: any) {
      const detail = err.response?.data?.error?.detail;
      if (detail && typeof detail === 'object') {
        const firstError = Object.values(detail)[0];
        setError(Array.isArray(firstError) ? firstError[0] : String(firstError));
      } else if (typeof detail === 'string') {
        setError(detail);
      } else {
        setError('Failed to create instrument. Please check all fields and try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  }

  const inputClass =
    'w-full px-3 py-2.5 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition';

  return (
    <form onSubmit={handleSubmit} className="space-y-7 max-w-2xl">

      {/* ── Instrument Name ── */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <label className="text-sm font-semibold text-gray-800">
            Instrument Name <span className="text-red-500">*</span>
          </label>
          <button
            type="button"
            onClick={() => {
              setNameMode(nameMode === 'dropdown' ? 'custom' : 'dropdown');
              setSelectedName('');
              setCustomName('');
            }}
            className="text-xs text-blue-600 hover:text-blue-800 font-medium underline underline-offset-2"
          >
            {nameMode === 'dropdown' ? '+ Enter a custom name instead' : '← Choose from list'}
          </button>
        </div>

        {nameMode === 'dropdown' ? (
          <div className="relative">
            <select
              value={selectedName}
              onChange={(e) => setSelectedName(e.target.value)}
              className={`${inputClass} appearance-none pr-9`}
              required
            >
              <option value="">— Select an instrument —</option>
              {INSTRUMENT_NAMES.map((n) => (
                <option key={n} value={n}>{n}</option>
              ))}
            </select>
            <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none" />
          </div>
        ) : (
          <input
            type="text"
            value={customName}
            onChange={(e) => setCustomName(e.target.value)}
            placeholder="Type the instrument name…"
            required
            className={inputClass}
          />
        )}
      </div>

      {/* ── Department ── */}
      <div className="space-y-2">
        <label className="text-sm font-semibold text-gray-800">
          Department <span className="text-red-500">*</span>
        </label>
        <div className="relative">
          <select
            value={formData.department}
            onChange={(e) => updateField('department', e.target.value)}
            className={`${inputClass} appearance-none pr-9`}
            required
          >
            {DEPARTMENTS.map((d) => (
              <option key={d} value={d}>{d}</option>
            ))}
          </select>
          <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none" />
        </div>
      </div>

      {/* ── Calibration Record ── */}
      <div className="border-t border-gray-200 pt-6 space-y-5">
        <h3 className="text-sm font-semibold text-gray-900">Initial Calibration Record</h3>

        {/* Dates */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Input
            label="Calibrated On"
            type="date"
            required
            value={formData.calibrated_on}
            onChange={(e) => updateField('calibrated_on', e.target.value)}
          />
          <Input
            label="Calibration Due Date"
            type="date"
            required
            value={formData.calibration_due_date}
            onChange={(e) => updateField('calibration_due_date', e.target.value)}
          />
        </div>

        {/* Notes */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-gray-800">Notes</label>
          <textarea
            value={formData.notes}
            onChange={(e) => updateField('notes', e.target.value)}
            rows={3}
            placeholder="Optional calibration notes…"
            className={`${inputClass} resize-none`}
          />
        </div>

        {/* File upload */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-gray-800">Calibration Report</label>
          <p className="text-xs text-gray-500">
            PDF, Excel, Word, images and other document formats are all accepted.
          </p>

          {reportFile ? (
            <div className="flex items-center gap-3 border border-gray-300 rounded-lg px-4 py-3 bg-blue-50">
              <FileText className="h-5 w-5 text-blue-600 shrink-0" />
              <span className="text-sm text-blue-800 flex-1 truncate font-medium">
                {reportFile.name}
              </span>
              <span className="text-xs text-gray-500 shrink-0">
                {(reportFile.size / 1024 / 1024).toFixed(2)} MB
              </span>
              <button
                type="button"
                onClick={clearFile}
                className="p-1 rounded-full hover:bg-blue-200 text-blue-600 transition"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          ) : (
            <label className="flex flex-col items-center gap-2 border-2 border-dashed border-gray-300 rounded-lg px-4 py-8 cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition group">
              <Upload className="h-6 w-6 text-gray-400 group-hover:text-blue-500 transition" />
              <span className="text-sm text-gray-500 group-hover:text-blue-600 transition font-medium">
                Click to upload a calibration report
              </span>
              <span className="text-xs text-gray-400">Any document format accepted</span>
              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,.xls,.xlsx,.doc,.docx,.csv,.txt,.png,.jpg,.jpeg,.bmp,.tiff"
                onChange={handleFileChange}
                className="hidden"
              />
            </label>
          )}
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-2 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg px-4 py-3">
          <span className="mt-0.5 shrink-0">⚠</span>
          <span>{error}</span>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-3 pt-1">
        <Button type="submit" isLoading={isSubmitting}>
          Create Instrument
        </Button>
        <Button type="button" variant="secondary" onClick={() => router.back()}>
          Cancel
        </Button>
      </div>
    </form>
  );
}

